Feature/publickey
cosmos-client/cosmos-client-ts pull request #58
Opened 2022-02-09 13:55 UTC by taro04

デバック中ですが、進捗共有のためPR作成します。

2022-02-15 02:56 UTC, KimuraYu45z commented on src/types/address/pubkey.ts
> +    if (privKey instanceof cosmos.crypto.secp256k1.PrivKey) {
実装内容問題ないのですが、実装してる箇所が気になりました。
ここのみが問題ですね。

以下、ed25519の公開鍵クラスの例です。
https://github.com/cosmos-client/cosmos-client-ts/blob/main/src/types/crypto/ed25519.ts#L36

ifで分岐すると抽象化ができてないことになるのもありますし、既存のed25519やsecp256k1の公開鍵の中にbech32エンコード用のメソッドを生やしたほうがいいのではないでしょうか？
PublicKeyはないほうが良いと思います。

2022-02-15 05:14 UTC, KimuraYu45z commented on src/types/address/pubkey.ts
> +    if (privKey instanceof cosmos.crypto.secp256k1.PrivKey) {
ちなみにですが、
https://github.com/cosmos-client/cosmos-client-ts/blob/main/src/types/crypto/ed25519.ts#L36
は、.protoから吐き出された公開鍵クラスに対して拡張メソッドのような方法でメソッドを生やしているやり方です。

2022-02-15 07:07 UTC, YasunoriMATSUOKA requested changes
@taro04
テストの書き方について、(prefix関連で)こうするとよいのではないかと思った点をコメントさせてもらいました。

まずはその点と、 @KimuraYu45z からのアドバイスを参考に、テストや今回加えた実装の整理をしてみるのが良いのではないかと思いました。

(勘違いしていたらすみませんが、)また、以下プルリクでコメント頂いた実装はこのプルリクのブランチに既に反映されていないように見えたので、必要あれば、それもこちらに反映して頂いて、テストの結果がどうなるかも見せて頂けるととても助かります。
https://github.com/CauchyE/telescope/pull/272#issuecomment-1034971103

@KimuraYu45z 
もし何か間違ったこと言っていたら、ご指摘頂けると助かります。

引き続きよろしくお願いします。

2022-02-15 12:33 UTC, taro04 commented
@KimuraYu45z 
コメントありがとうございます。
いただいた例を参考にメソッドを追加する形で実装しなおしました。

@YasunoriMATSUOKA 
コメントありがとうございます。setPrefix関数の意味が理解できました。
またテストも極力既存のものは触らず、新たにaccPublicKey.spec.tsを作成しました。
（すみませんpretterの影響で一部変わっているところあります。）

・ed25519の実装とテストについて

```
  ● address › ed25519

    expect(received).toBe(expected) // Object.is equality

    Expected: "ununifipub1addwnpepq0u4zl9r2x4ks82mjetexffsdduruqkmmtmqnx68dfkuy2yr275e53rn0e4"
    Received: "ununifipub1addwnpep7cvz04pv5fde2ayzd4kfjlv0zsv86mgku5cmg9uj0ept6cewsqps6hjpd6"
```


作成していたアカウントがscep256k1秘密鍵のものだったので、
ed25519でのテストは通っていません。（それ以外は通っています。）

そこでununifiedでed25519秘密鍵を作成しようとしましたが作成できませんでした。

入力コマンド
`ununifid keys add tsunoda-debug-ed25519 --algo ed25519` ( `--algo tm-ed25519`も同様。)

starportで作成する方法も検討しましたが、
cosmospub～形式の公開鍵が表示されなかったです。

ed25519公開鍵について何か確認する方法ありましたら
ご教示いただけますようお願いいたします。

2022-02-15 12:35 UTC, taro04 commented on src/types/crypto/ed25519.ts
> +  const prefix = new Uint8Array([235, 90, 233, 135, 33]);
ここでprefixを演算していないのが多少気にはなっています。

2022-02-15 12:36 UTC, taro04 commented on src/types/crypto/ed25519.ts
> +  mergedKey.set(this.key, prefix.length);
const でUint8Arrayをマージする方法あればご教示いただきたくお願いいたします。

2022-02-16 00:57 UTC, KimuraYu45z commented
ununifidではed25519作れないのはcosmos sdkの仕様です（あるアップデートからそうなりました）

普通にspecのコードで秘密鍵生成とed25519公開鍵を作成してください。

2022-02-16 05:25 UTC, YasunoriMATSUOKA commented on src/types/crypto/ed25519.ts
> +  mergedKey.set(this.key, prefix.length);
ここのコメントの件は、letをconstにすればいいんじゃないでしょうか？と思ったのですが、もしそれ以外の何かがあったら、教えて頂けると助かります。

2022-02-16 05:35 UTC, YasunoriMATSUOKA commented on src/types/crypto/ed25519.ts
> +  const prefix = new Uint8Array([235, 90, 233, 135, 33]);
@KimuraYu45z 
ここが、このプルリクで、現時点で原理的に未解決の箇所だと思います。(secp256k1.ts も同じ。)

ハードコードしてよいような値なのでしょうか？

また、 @taro04  にて検討頂いたロジック( https://github.com/CauchyE/telescope/pull/272#issuecomment-1034971103 )だと、ここは別の値になるのでは？という議論があったと思うのですが、それだとUnUniFiのununifidのコマンドで出力される文字列化された公開鍵と一致せず、そこが一致するように値を書き換えてハードコードしているという現状だと思うので、そこがなぜどのように違うのかを明確化せずにこのまま進むことに危うさを感じているというのが @YasunoriMATSUOKA  の所感です。

@KimuraYu45z 
申し訳ありませんが、松岡ではこれ以上有益な助言ができそうになく、問題解決のために @taro04 に対し、もう少し踏み込んだサポート頂けると助かります。お手数ですがよろしくお願いします。

2022-02-16 05:47 UTC, YasunoriMATSUOKA commented on src/types/address/accPublicKey.spec.ts
> +});
@taro04 
このファイル `src/types/address/accPublicKey.spec.ts` に書かれたテストは `accPubKey()` のテストだと思います。
その `accPubKey()` の実体は、 `src/types/crypto/secp256k1.ts` と `src/types/crypto/ed25519.ts` に書かれていると思うので、それぞれ、 `src/types/crypto/secp256k1.spec.ts` と `src/types/crypto/ed25519.spec.ts` にテストが追加で書かれるとわかりやすいのではないかと思いました。

2022-02-16 05:48 UTC, KimuraYu45z commented on src/types/crypto/ed25519.ts
> +  const prefix = new Uint8Array([235, 90, 233, 135, 33]);
ここはコメントで
```ts
// TODO
```
を置きつつ、テストが通るのであればいったんGOでいきましょう。

次やるなら
```
[235, 90, 233, 135, 33,]
```
が base128Varintsで何を意味するのかの調査な気がします。

2022-02-16 05:58 UTC, YasunoriMATSUOKA commented on src/types/crypto/ed25519.ts
> +  const prefix = new Uint8Array([235, 90, 233, 135, 33]);
@KimuraYu45z 
テストはUnUniFiのbech32Prefixの場合(ununifipub)と、Cosmos SDKデフォルト的なbech32Prefixの場合(cosmospub)の両方をやったほうが良いと思っていますが認識あっているでしょうか？(このプルリクの件に関して、現状はUnUniFiのテストしかない状態だと思います。)

2022-02-16 06:03 UTC, KimuraYu45z commented on src/types/crypto/ed25519.ts
> +  const prefix = new Uint8Array([235, 90, 233, 135, 33]);
はい、両方やるのがいいと思います。

2022-02-16 06:14 UTC, YasunoriMATSUOKA commented
@taro04 

以降の実装方針は以下コメント群のやり取りを参考にして進めてもらえると助かります。

https://github.com/cosmos-client/cosmos-client-ts/pull/58#discussion_r806784204
https://github.com/cosmos-client/cosmos-client-ts/pull/58#discussion_r806785159

@KimuraYu45z 

追加でもう一点質問させてください。以下リンクの件、ed25519のニーモニックと公開鍵と文字列化された公開鍵の正しいと確信できる組み合わせを、このレポジトリのSDKに依存せずに得る方法が何かあるでしょうか？

https://github.com/cosmos-client/cosmos-client-ts/pull/58#issuecomment-1040957908

もしないのであれば、今回の件のed25519に関する実装は本当の意味でテストできない気がしていて、良い方法ないかアドバイス頂けると助かります。(というか、実際にはed25519をこのSDKを通じて利用することは現状だとなさそうなので、ed25519関連の公開鍵の実装が間違っていても特に問題はない？このあたり勘違いしていたらすみませんが、自分が明確に理解できていないと思ったので、念のためこの機会に確認させてください。)

2022-02-16 06:19 UTC, KimuraYu45z commented
cosmos client tsが依存しているnaclのライブラリを直接使ってed25519の鍵ペア作ることはできますね。
ただしその公開鍵のbech32エンコードをどう取得するのかっていうと少々難しいですね。


なんでdaemonがサポートしてないかっていうと、

```
~/.ununifi/config/priv_validator_key.json
```

(configじゃなくてdataかも)

ここに書いてある鍵（ブロックチェーンコンセンサス用の鍵）がed25519で、残高管理の鍵はsecp256k1、って棲み分けをするようになったから（多分）ので、initコマンドをローカル自PCでやってみて、 `~/.ununifi/config/priv_validator_key.json`の中身をみてみるとかもいいかもしれません。

2022-02-16 06:23 UTC, YasunoriMATSUOKA commented
@KimuraYu45z 
ありがとうございます。(最悪、時間かかりそうだったら、そこもコメント残して、スキップする方向で進めようと思います。)

@taro04 
このあたりも参考にしつつ、進めて頂けると助かります。

2022-02-16 06:24 UTC, KimuraYu45z commented
`~/.ununifi/config/priv_validator_key.json`に書いてあるpubkeyとprivkey両方bech32デコードして、そのprivkeyからそのpubkeyが正しく導出されるか確認すればテストとして成り立つような気がしました。

2022-02-16 06:37 UTC, YasunoriMATSUOKA commented
@KimuraYu45z 
ありがとうございます。念のため確認させてください。

これはローカルにあった適当なチェーン(chain_idとか諸々違うので参考にならない)のデータを仮に示しますが、例えば、以下のような情報がファイル内に書かれていたとして、これをまず `unpackAny` して、そのデータに対してテストを書いていくようなイメージであっているでしょうか？

```json
"pub_key": {
    "type": "tendermint/PubKeyEd25519",
    "value": "Vb6L2ZLlh9YX2dFbCfK0wARbOIH9vYz5OfjYOy0HUVA="
  },
```

なお、現状稼働しているパブリックテストネットノードの対象ファイルの情報を使ってここにテストを実装して公開するのはNGであることに注意が必要なのかなと思っていますが、認識あっているでしょうか？

2022-02-16 06:41 UTC, KimuraYu45z commented
はい、必ずローカルで自PCでinitすることにより新たに生成した鍵をテストに書くようにしてください。それなら誤って秘密鍵が混入しても捨てたらいいだけにできますし。

おっしゃる通りそれはunpackが必要な形式でしたね。
tendermintコマンドかなんかでそれのbech32エンコードの値が出せたと思います。

2022-02-16 06:42 UTC, YasunoriMATSUOKA commented
@KimuraYu45z 
ありがとうございます。

@taro04 
上記やり取り参考に再度検討してみて頂けると助かります。
引き続きよろしくお願いします。

2022-02-16 12:06 UTC, taro04 commented on src/types/crypto/ed25519.ts
> +  mergedKey.set(this.key, prefix.length);
@KimuraYu45z 
現在の設定だと、...Uint8Arrayが使えないようです。

>型 'Uint8Array' は配列型でも文字列型でもありません。反復子の反復を許可するには、コンパイラ オプション '--downlevelIteration' を使用します。ts(2569)

@YasunoriMATSUOKA 
後から要素を代入するのでconstで定義することに違和感ありましたが、
試したらletをconstでいけました。ありがとうございます。

2022-02-16 12:21 UTC, KimuraYu45z commented on src/types/crypto/ed25519.ts
> +  mergedKey.set(this.key, prefix.length);
constはそのものへの代入不可なだけでフィールドの編集は全然可能ですね。

2022-02-16 14:03 UTC, taro04 commented
・ローカルにutils/chainをインストールして、`init` し、`~/.ununifi/config/priv_validator_key.json` から
以下のデータを取得しました。
```
  "address": "19647C2DC80B9A8C78A3BEA49A5878580235851F",
  "pub_key": {
    "type": "tendermint/PubKeyEd25519",
    "value": "+q8dUtYeppa3ycdKFIc1Dl9OtVLbTVlXoBpmsOO4p40="
  },
  "priv_key": {
    "type": "tendermint/PrivKeyEd25519",
    "value": "Q7RecOq++QctQfKXqBOnrvMIT81sC8KaIE+HY+ZfsOn6rx1S1h6mlrfJx0oUhzUOX061UttNWVegGmaw47injQ=="
  }
```
データ取得後に、以下試しましたが、うまいことアカウントの情報を得られず、
アドバイスいただけないでしょうか。


１．unpackできない。
具体的には `unpackAny()` にはvalueがUint8Arrayでないので入らず、 `unpackAnyCosmos()` は何も起こらない状況です。
[https://github.com/cosmos-client/cosmos-client-ts/pull/58/files#diff-8a761555b953b8600af412eb297431babe3da8b8200e46efa3c0495cbc288796R17-R31](https://github.com/cosmos-client/cosmos-client-ts/pull/58/files#diff-8a761555b953b8600af412eb297431babe3da8b8200e46efa3c0495cbc288796R17-R31)

２．unpackしない方法として、
>tendermintコマンドかなんかでそれのbech32エンコードの値が出せたと思います。

`ununifid tendermint [command]` にBech32エンコードのコマンドが見当たりませんでした。
```
Available Commands:
  show-address   Shows this node's tendermint validator consensus address
  show-node-id   Show this node's ID
  show-validator Show this node's tendermint validator info
  version        Print tendermint libraries' version
```
なにか勘違いしてたらすみません。

３．その他の方法として、
>テスト用のデータを一組作るには、ローカルでCosmos SDK v0.42.x系の状態でstarportコマンド

こちらも試してみようと、starport v0.17.0を入れてみましたが、
（starportはv0.18.0からCosmos SDK v0.44）
`starport account create` コマンドが無くアカウント作ることが出来ませんでした。
starport v0.17.0の環境でアカウントを作成する方法をご存じでしたら、ご教示いただきたくお願いいたします。
こちらもなにか勘違いしてたらすみません。

2022-02-17 08:45 UTC, KimuraYu45z commented
まっつぁんのコメント共有

正しいと確信できる以下のペアの組み合わせがほしい状況だと思います(ed25519は今は使っていないので優先度低くて良いかもなので、その場合は、一旦保留的な判断もありなのかなと思っています。)
- secp256k1 UnUniFiのbech32Prefixでの秘密鍵、公開鍵の組み合わせ
- secp256k1 Cosmos SDKデフォルトのbech32Prefixでの秘密鍵、公開鍵の組み合わせ
- ed25519 UnUniFiのbech32Prefixでの秘密鍵、公開鍵の組み合わせ
- ed25519 Cosmos SDKデフォルトのbech32Prefixでの秘密鍵、公開鍵の組み合わせ

2022-02-17 09:18 UTC, KimuraYu45z commented
unpackCosmosAnyには  `type`でなく `@type`である必要もありますね
https://github.com/UnUniFi/chain/blob/develop/launch/ununifi-8-private-test/genesis-pretty.json#L46

2022-02-17 14:41 UTC, taro04 commented
@KimuraYu45z 

>おそらく "tendermint/PrivKeyEd25519" となっているほうがわるくて、 "/cosmos.crypto.ed25519.PrivKey" に書き換えてやってみると良いかもなと思いました。

[https://github.com/cosmos-client/cosmos-client-ts/pull/58/files#diff-8a761555b953b8600af412eb297431babe3da8b8200e46efa3c0495cbc288796R17-R32](https://github.com/cosmos-client/cosmos-client-ts/pull/58/files#diff-8a761555b953b8600af412eb297431babe3da8b8200e46efa3c0495cbc288796R17-R32)

リンクも参考に` type`, `@type`,や,` value`, `priv_key`などいくつか試してみたのですが、
すみません、やはりunpackできませんでした。

>appd keys addする

starport v0.17.0のコマンドに `appd keys add` がありませんでした。

と、私の方でこれ以上探しても時間かけるだけだと思ったので、
secp256k1 ununifi のテスト結果のみで進める、
もしくは下記の組み合わせの鍵の情報をいただけないでしょうか。

>secp256k1 UnUniFiのbech32Prefixでの秘密鍵、公開鍵の組み合わせ
secp256k1 Cosmos SDKデフォルトのbech32Prefixでの秘密鍵、公開鍵の組み合わせ
ed25519 UnUniFiのbech32Prefixでの秘密鍵、公開鍵の組み合わせ
ed25519 Cosmos SDKデフォルトのbech32Prefixでの秘密鍵、公開鍵の組み合わせ

なお厳密には、ニーモニックもしくはUint8Arrayの秘密鍵と、Bech32エンコード済みの公開鍵、
が必要だと思っています。

2022-02-18 01:37 UTC, KimuraYu45z commented
`value`は根拠わかりますが、 `priv_key`はなにを根拠に試されましたか？

2022-02-18 01:37 UTC, KimuraYu45z commented
appdってのはstarportのコマンドじゃなくてstarportで作ったdaemonの例なので、、例えばununifidに置き換えないといけません。

2022-02-18 03:37 UTC, KimuraYu45z commented
secp256k1の公開鍵は現状bech32エンコードされることがないので

```
ed25519 UnUniFiのbech32Prefixでの秘密鍵、公開鍵の組み合わせ
ed25519 Cosmos SDKデフォルトのbech32Prefixでの秘密鍵、公開鍵の組み合わせ
```

だけ作りますね。

```
yu@DESKTOP-P0C9BVB ~/.gaia/config
 % cat priv_validator_key.json       
{
  "address": "636099512DF7F930ABF5630FA15D6BEC5AB621F9",
  "pub_key": {
    "type": "tendermint/PubKeyEd25519",
    "value": "npQgsc3bwIOe1wmya7PUWpInDCfk+UxsjpexWSuWDJY="
  },
  "priv_key": {
    "type": "tendermint/PrivKeyEd25519",
    "value": "DpF2T8MKQUidqRtWwxlw4rAqbiZoXJE/ziN4thBLWEuelCCxzdvAg57XCbJrs9RakicMJ+T5TGyOl7FZK5YMlg=="
  }
}%                                                                                                                                                                                                                        
yu@DESKTOP-P0C9BVB ~/.gaia/config
 % cat node_key.json                                
{"priv_key":{"type":"tendermint/PrivKeyEd25519","value":"4QhG0/HWN8WXey0KfmL90uy9TnP5+nrgHlm/AQLsgzdp+1/i2y1ephohX9uir8jV3foXsX2SiK/zG8GGGe8Rxg=="}}%                                                                     
yu@DESKTOP-P0C9BVB ~/.gaia/config
 % gaiad tendermint show-validator
{"@type":"/cosmos.crypto.ed25519.PubKey","key":"npQgsc3bwIOe1wmya7PUWpInDCfk+UxsjpexWSuWDJY="}
```

どうやら `@type`と`key` でunpackできそうですね。`value`でも`priv_key`でもなく。

> しかし、Cosmos SDK v0.44.x以降だと、bech32エンコードの値を文字列として表示してくれるわけではなく、packされた型のようなJSONを表示する実装にCLIが変わっているように見えました。

ここのことです。

2022-02-18 03:38 UTC, KimuraYu45z commented
keyだったらunpackできると思うので俺が作るまでもないと思います。そのままテストコード修正して進めてください。

2022-02-18 04:10 UTC, YasunoriMATSUOKA commented
@KimuraYu45z 
secp256k1の公開鍵(普通のアカウントの公開鍵)は、bech32エンコードして表示しないのがCosmos SDK製ブロックチェーンのデファクトスタンダードですか？

ununifid keys add のcliコマンドで鍵生成したときとか、ununifid keys listとかで鍵一覧表示したときに、bech32エンコードされた公開鍵が表示されていた気がしていて、むしろsecp256k1の方でこをbech32エンコードした公開鍵表示が必要なのでは？と思っていたのですが、何か勘違いしているでしょうか？

逆にed25519の公開鍵を(Telescope等で)普通のアカウントとして使っていないので、ed25519の方のbech32エンコードの方が不要なのではと思っていたのですが、こちらも何か勘違いしているでしょうか？

2022-02-18 04:11 UTC, KimuraYu45z commented
あーそうだkeys listでsecp256k1のbech32やってましたね。失礼。

ed25519はv0.42のshow-validatorがそれです。

てことはやっぱ両方要りますね。

2022-02-18 14:10 UTC, taro04 commented
@KimuraYu45z 
ご確認ありがとうございます。

>secp256k1 UnUniFiのbech32Prefixでの秘密鍵、公開鍵の組み合わせ
secp256k1 Cosmos SDKデフォルトのbech32Prefixでの秘密鍵、公開鍵の組み合わせ
ed25519 UnUniFiのbech32Prefixでの秘密鍵、公開鍵の組み合わせ
ed25519 Cosmos SDKデフォルトのbech32Prefixでの秘密鍵、公開鍵の組み合わせ

現状のテスト結果まとめます。

①scep256k1/ununifi・・・OK
　[データ]：ununifidでアカウント作成し、bech32エンコード公開鍵とニーモニックを得る。
　　ニーモニックから自作したbech32エンコード公開鍵と、得られたbech32エンコード公開鍵を比較

②scep256k1/cosmos・・・未
　[データ]：starport（v0.19.3）でアカウント作成し、string公開鍵とニーモニックを得る。
　　bech32エンコード公開鍵の取得方法が不明。
　　　　　
③ed25519/ununifi・・・NG
　[データ]ununifid,initでValアカウント作成し、公開鍵と秘密鍵を得る。
　　unpackした秘密鍵から自作したbech32エンコード公開鍵と、
　　show-validatorコマンドから得られたbech32エンコード公開鍵を比較。

④scep256k1/cosmos・・・未
　[データ]木村さんの方でlアカウント作成し、公開鍵と秘密鍵を得る。
　　unpackした秘密鍵から自作したbech32エンコード公開鍵と、
　　show-validatorコマンドから得られたbech32エンコード公開鍵を比較。


②について、CLIで得られる公開鍵が`{0301DC2818F675A3CC39B8F41C73CB3F98D257DBBB8994D933518F57494A6FC74D}`の形式なのでbech32エンコード公開鍵が必要です。
コメントいただいたようにununifidと同様の機能でprefixがCosmosのものがあれば、`key add `で得られると思うのですが、何かありますでしょうか。

③でテスト結果が以下です。公開鍵の長さが32と33で違うので当然ですが、ハードコーディングしてるprefixで引っかかっています。
![image](https://user-images.githubusercontent.com/75844498/154695526-377cd54f-54f4-4bf6-9d90-9cb4eabd12ec.png)

④について、show-validatorコマンドの結果を教えていただけると幸いです。


ちなみに` priv_key`は以下を参考にしたものでした。
[https://github.com/UnUniFi/chain/blob/develop/launch/ununifi-8-private-test/genesis-pretty.json#L48](https://github.com/UnUniFi/chain/blob/develop/launch/ununifi-8-private-test/genesis-pretty.json#L48)`

2022-02-19 05:44 UTC, KimuraYu45z commented
```
yu@DESKTOP-P0C9BVB ~ % gaiad keys add hoge --keyring-backend test

- name: hoge
  type: local
  address: cosmos154qxsq0mfcx5gr7hpayr2uqcdt844u78xe6h98
  pubkey: '{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"A8Pj5Q8u3hShw3+oFc4nGrZvKl4avTDHW1m9GiI1fm5x"}'
  mnemonic: ""


**Important** write this mnemonic phrase in a safe place.
It is the only way to recover your account if you ever forget your password.

joy furnace inject spot engine source alpha turn east visa abstract cousin shell express weasel math perfect tiger quality camp mansion desert web jaguar
```

このmnemonicから秘密鍵導出もできるので試してください。

2022-02-21 14:29 UTC, taro04 commented
@KimuraYu45z , @YasunoriMATSUOKA 

テスト通るようになったので、現状のテスト結果を以下まとめます。


①scep256k1/ununifi・・・OK
　[データ]：ununifidでアカウント作成し、bech32エンコード公開鍵とニーモニックを得る。
　　ニーモニックから自作したbech32エンコード公開鍵と、得られたbech32エンコード公開鍵を比較

②scep256k1/cosmos・・・OK
　[データ]木村さんの方でアカウント作成し、公開鍵と秘密鍵を得る。
　　unpackした秘密鍵から自作したbech32エンコード公開鍵と、
　　ニーモニックから取得したbech32エンコード公開鍵を比較。

③ed25519/ununifi・・・OK
　[データ]ununifid,initでValアカウント作成し、公開鍵と秘密鍵を得る。
　　unpackした秘密鍵から自作したbech32エンコード公開鍵と、
　　show-validatorコマンドから得られたbech32エンコード公開鍵を比較。

④ed25519/cosmos・・・OK
　[データ]：starportで適当なチェーンを立ち上げ、
　　unpackした秘密鍵から自作したbech32エンコード公開鍵と、
　　unpackした公開鍵bech32エンコード公開鍵を比較。

お手数ですが、ご確認お願い致します。

2022-03-22 07:58 UTC, YasunoriMATSUOKA requested changes
@taro04 cc: @KimuraYu45z 
対応ありがとうございました。

一通りレビューさせてもらって、このプルリクで実装頂いた内容はおおむね問題ないように見えました。

ただ、自動テスト、Linter & Formatter的なところでこの機会に以下修正しておいたほうがよいのではないかと感じた点をコメントさせてもらいました。

もし、レビュー内容に違和感あれば、遠慮なくご指摘頂けると助かります。
よろしくお願いします。

npm run testを実行した結果、今回のPRと関係ない、src/websocket/websocket.spec.ts がfailしていました。CI環境ではlocalhost:26657にテストが実装されたような振る舞いをするwebsocketは存在しないと思うので、一旦、websocketのテストコードはコメントアウトして、ダミーのテストコードとしてexpect(true).toBeTruthy()的な形にしておいて、GitHub ActionsのCIのnpm run testを有効化しておいてはいかがでしょうか？

```
FAIL  src/websocket/websocket.spec.ts
  ● websocket › websocket

    ReferenceError: WebSocket is not defined

      14 |
      15 | export function connect(url: string) {
    > 16 |   const ws = new WebSocketSubject<RequestSchema | ResponseSchema>({
         |              ^
      17 |     url: `${url}/websocket`,
      18 |   });
      19 |

      at new WebSocketSubject (node_modules/rxjs/src/internal/observable/dom/WebSocketSubject.ts:181:36)
      at Object.connect (src/websocket/module.ts:16:14)
      at src/websocket/websocket.spec.ts:14:26
      at src/websocket/websocket.spec.ts:8:71
      at Object.<anonymous>.__awaiter (src/websocket/websocket.spec.ts:4:12)
      at Object.<anonymous> (src/websocket/websocket.spec.ts:12:30)
```

Linter, Formatter的に警告が表示されているところがいくつかあり、実装修正すべきものであれば修正、実装修正する必要はないものであれば警告表示を対象箇所だけ無効化等しておくとよいかなと思った箇所がいくつかあったのでソースコード中にコメントしておきました。

また、こちらも実装自体に問題はないものの、`src/types/crypto/key.spec.ts` の中の toStrictEqualはtoBeにするのを推奨されているように見えました。(自分の環境だと、toBeに自動的にFormatterで修正されたので、そうしておいたほうが良いのかな？と思いました。)
![image](https://user-images.githubusercontent.com/55148923/159432609-0634719e-3d42-43c4-8b6b-d32800b7838e.png)

2022-03-22 07:58 UTC, YasunoriMATSUOKA commented on src/types/crypto/ed25519.spec.ts
>    console.log(str);
@taro04 cc: @KimuraYu45z 
この箇所、PRとは関係ないですが、以下のスクショのような警告がエディタ上表示されていて、不要であれば、このconsole消してもいいかなとも思ったのですが、いかがでしょうか？
![image](https://user-images.githubusercontent.com/55148923/159430328-c6f24d00-3899-42fd-a232-82e35d29d941.png)

2022-03-22 07:58 UTC, YasunoriMATSUOKA commented on src/types/crypto/ed25519.ts
>    }
@taro04 cc: @KimuraYu45z 
ここの箇所、PRの変更とは関係ないのですが、以下のような警告が出る状況に見えます。おそらく機能としては問題ないと思いますが、そうであればこの箇所のみ、明示的にこのESLintの警告を無効化しておく等するのが好ましいかな？と思ったのですがいかがでしょうか？secp255k1の方も同様の箇所があるように見えました。
![image](https://user-images.githubusercontent.com/55148923/159430914-719469e1-8520-451e-80b3-b2e55418976b.png)

2022-03-24 12:13 UTC, taro04 commented on src/types/crypto/ed25519.ts
>    }
以下の記事参考に、コメントでこの宣言だけES Lint の no-unused-vars を無効にしました。
[https://qiita.com/nju33/items/2d0cfea4fffbfdbff87a](https://qiita.com/nju33/items/2d0cfea4fffbfdbff87a)

2022-03-24 12:40 UTC, taro04 commented
@YasunoriMATSUOKA 

以下、修正完了しました。

・websocketのtest通るように、コメントアウト。
・不要なStrictEqualをtoBeへ。
　（型があっているのは自明だからstrictにする必要ない、ってことだと理解しました。）
・不要な回路削除。
・ES Lint でどうしてもエラー出る箇所のは、ES Lint無効化。

ご確認お願い致します。

2022-03-25 10:23 UTC, YasunoriMATSUOKA approved these changes
@taro04 
![LGTM](https://image.lgtmoon.dev/77606)

2022-03-25 10:24 UTC, merged